name: SAFA-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch :
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: init
      uses: actions/checkout@v2
    - name: Set Build Number
      run: echo "::set-env name=BUILD_VER::v1.$GITHUB_RUN_NUMBER"
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
    - name: Docker Build
      run: docker build -t mostefaiamine/safa-app:${{ env.BUILD_VER }} .
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Docker tag
      run:  docker tag mostefaiamine/safa-app:${{ env.BUILD_VER }} hisregistry/demoigf:latest   
    - name: Docker push
      run:  |
        docker push mostefaiamine/safa-app:${{ env.BUILD_VER }}     
        docker push mostefaiamine/safa-app:latest   
      env: 
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
